#!/bin/bash

if ! wget --no-verbose --recursive --no-parent --no-host-directories --execute robots=off \
--reject "index.html*" --exclude-directories .git "$(cat "$(dirname $0)/.host_address"):8080"
then
    echo "cannot get project from server"
    exit 1
fi

make clean
make
./router < input.txt
