#!/bin/bash

ip link set up enp0s3
ip link set up enp0s8
ip addr add 10.0.1.2/8 dev enp0s3
ip addr add 172.16.1.13/16 dev enp0s8

echo $'2\n10.0.1.2/8 distance 3\n172.16.1.13/16 distance 4\n' > input.txt
