#!/bin/bash

ip link set up enp0s3
ip link set up enp0s8
ip addr add 172.16.1.14/16 dev enp0s3
ip addr add 192.168.2.10/24 dev enp0s8

echo $'2\n172.16.1.14/16 distance 4\n192.168.2.10/24 distance 2\n' > input.txt
