#!/bin/bash

ip link set up enp0s3
ip link set up enp0s8
ip addr add 192.168.5.43/24 dev enp0s3
ip addr add 10.0.1.1/8 dev enp0s8

echo $'2\n192.168.5.43/24 distance 2\n10.0.1.1/8 distance 3' > input.txt
