#!/bin/bash

ip link set up enp0s3
ip link set up enp0s8
ip addr add 192.168.2.5/24 dev enp0s3
ip addr add 192.168.5.5/24 dev enp0s8

echo $'2\n192.168.2.5/24 distance 2\n192.168.5.5/24 distance 2\n' > input.txt
